#!/usr/bin/env python3
"""
llm_shotlist_latentsync.py - LLM-directed shot list for LatentSync pipeline.

Reads:
  - beatmap.json     (from audio_analysis.py — includes vocal_active flags per section)
  - lyrics.txt       (Suno lyrics, plain text)
  - singer_ref_images/  (1 or more reference images of the singer)
  - broll_ref_images/   (reference images for B-roll scenes)

Calls an LLM to produce a shot list with three scene types:
  - "singer_latentsync" → singer on camera, base video generated by LTX/Wan
                          (workflow 01/02), then LatentSync applied (workflow 05),
                          then face-restore post-FX (workflow 06)
  - "broll"             → cinematic B-roll, no singer (workflow 03/04 + workflow 07)

DECISION LOGIC (LLM is given these rules):
  • Verses (vocal_active=true, label starts with "verse") → singer_latentsync
  • Choruses → broll (choruses work better as visually dynamic B-roll)
  • Intro / outro / instrumental breaks → broll
  • Bridge → broll

USAGE:
    export ZAI_API_KEY="..."
    python llm_shotlist_latentsync.py \\
        --beatmap beatmap.json \\
        --lyrics lyrics.txt \\
        --singer-dir singer_ref_images/ \\
        --broll-dir broll_ref_images/ \\
        --output shotlist.json \\
        --send-images

OUTPUT SCHEMA (shotlist.json):
{
  "song_title": "...",
  "bpm": 124.0,
  "total_duration": 215.4,
  "singer_ref_image": "singer_01.png",
  "scenes": [
    {
      "index": 0,
      "start_time": 0.0,
      "end_time": 12.5,
      "section": "intro",
      "scene_type": "broll",
      "ref_image": "city_skyline_night.png",
      "prompt": "cinematic aerial shot, neon-lit city skyline at night, ...",
      "negative_prompt": "blurry, low quality, ...",
      "model": "ltx",
      "motion_strength": 0.4,
      "duration_sec": 12.5,
      "notes": "Long establishing shot..."
    },
    {
      "index": 1,
      "start_time": 12.5,
      "end_time": 36.8,
      "section": "verse1",
      "scene_type": "singer_latentsync",
      "ref_image": "singer_01.png",
      "base_model": "wan",
      "vocal_audio_segment": "vocal_segment_001.wav",
      "prompt": "cinematic close-up of singer, head and shoulders, subtle head motion, dramatic rim lighting, ...",
      "negative_prompt": "blurry, distorted face, ...",
      "motion_strength": 0.3,
      "latentsync_mask_strength": 0.7,
      "duration_sec": 24.3,
      "notes": "Singer performing verse 1; LatentSync will add lip-sync"
    }
  ]
}
"""
import argparse
import base64
import json
import os
import sys
from pathlib import Path

try:
    import requests
except ImportError:
    print("ERROR: missing 'requests'. Run: pip install requests")
    sys.exit(1)


def _encode_image_b64(path: str) -> str:
    with open(path, "rb") as f:
        return base64.b64encode(f.read()).decode("utf-8")


def _image_mime(path: str) -> str:
    ext = Path(path).suffix.lower().lstrip(".")
    return {"jpg": "image/jpeg", "jpeg": "image/jpeg", "png": "image/png", "webp": "image/webp"}.get(ext, "image/jpeg")


def call_zai(prompt, images, model, temperature, max_tokens):
    api_key = os.environ.get("ZAI_API_KEY")
    if not api_key:
        raise RuntimeError("ZAI_API_KEY env var not set.")
    url = os.environ.get("ZAI_BASE_URL", "https://open.bigmodel.cn/api/paas/v4/chat/completions")
    content = [{"type": "text", "text": prompt}]
    if images:
        for img_path in images:
            content.append({"type": "image_url", "image_url": {"url": f"data:{_image_mime(img_path)};base64,{_encode_image_b64(img_path)}"}})
    payload = {
        "model": model,
        "messages": [
            {"role": "system", "content": "You are a music video director with expertise in cinematic shot design, beat-synced editing, and lip-sync performance direction. You output strictly valid JSON when asked."},
            {"role": "user", "content": content},
        ],
        "temperature": temperature, "max_tokens": max_tokens,
    }
    headers = {"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"}
    r = requests.post(url, headers=headers, json=payload, timeout=120)
    r.raise_for_status()
    return r.json()["choices"][0]["message"]["content"]


def call_openai(prompt, images, model, temperature, max_tokens):
    api_key = os.environ.get("OPENAI_API_KEY")
    if not api_key:
        raise RuntimeError("OPENAI_API_KEY env var not set.")
    url = "https://api.openai.com/v1/chat/completions"
    content = [{"type": "text", "text": prompt}]
    if images:
        for img_path in images:
            content.append({"type": "image_url", "image_url": {"url": f"data:{_image_mime(img_path)};base64,{_encode_image_b64(img_path)}"}})
    payload = {
        "model": model,
        "messages": [
            {"role": "system", "content": "You are a music video director with expertise in cinematic shot design, beat-synced editing, and lip-sync performance direction. You output strictly valid JSON when asked."},
            {"role": "user", "content": content},
        ],
        "temperature": temperature, "max_tokens": max_tokens,
    }
    headers = {"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"}
    r = requests.post(url, headers=headers, json=payload, timeout=180)
    r.raise_for_status()
    return r.json()["choices"][0]["message"]["content"]


def call_ollama(prompt, images, model, temperature, max_tokens):
    base = os.environ.get("OLLAMA_BASE_URL", "http://localhost:11434")
    url = f"{base}/api/chat"
    images_b64 = [_encode_image_b64(p) for p in (images or [])]
    payload = {
        "model": model,
        "messages": [
            {"role": "system", "content": "You are a music video director with expertise in cinematic shot design, beat-synced editing, and lip-sync performance direction. You output strictly valid JSON when asked."},
            {"role": "user", "content": prompt, "images": images_b64},
        ],
        "stream": False, "options": {"temperature": temperature, "num_predict": max_tokens},
    }
    r = requests.post(url, json=payload, timeout=600)
    r.raise_for_status()
    return r.json()["message"]["content"]


PROVIDERS = {
    "zai":     (call_zai,     "glm-4v-plus"),
    "openai":  (call_openai,  "gpt-4o"),
    "ollama":  (call_ollama,  "llama3.1:70b"),
}


DIRECTOR_PROMPT_TEMPLATE = """\
You are directing a music video for the song below. The video MIXES two kinds of scenes:
  - SINGER shots: singer on camera, head + shoulders, head mostly still.
                  Base video is generated with LTX or Wan + IP-Adapter FaceID
                  (locks the singer's identity from a reference image).
                  LatentSync 1.5 then re-renders the mouth to sync with vocals.
  - B-ROLL shots: cinematic environments, NO singer visible.

Visual style: cinematic — Blade Runner 2049, The Weeknd "Blinding Lights",
Villeneuve's Dune. Photorealistic, shallow DOF, anamorphic lens flares, film grain.

== SONG METADATA ==
- Title: {title}
- BPM: {bpm}
- Duration: {duration:.1f}s
- Time signature: {ts}

== SONG SECTIONS (with vocal-active flags) ==
{sections_block}

== LYRICS ==
{lyrics}

== AVAILABLE SINGER REFERENCE IMAGES (for singer shots) ==
{singer_listing}

== AVAILABLE B-ROLL REFERENCE IMAGES (for B-roll shots) ==
{broll_listing}

== TASK ==
Design a shot list. Each scene MUST:
1. Start and end on a section boundary from above.
2. Be tagged scene_type = "singer_latentsync" OR "broll":
   • verse + vocal_active=true → "singer_latentsync"
   • chorus (any vocal_active) → "broll"
   • intro / outro / instrumental / bridge → "broll"
3. For SINGER_LATENTSYNC scenes:
   - ref_image = ONE singer image (use exact filename)
   - prompt describes CAMERA + LIGHTING + MOOD, not the singer's appearance
     (IP-Adapter FaceID handles appearance from the ref image)
   - ALWAYS include "subtle head motion" and "head and shoulders visible"
   - NEVER mention "singing", "talking", "mouth open", "lip-sync"
     (LatentSync will add the mouth motion later)
   - motion_strength: 0.2-0.4 (LOW — head must stay stable for LatentSync)
   - base_model: "ltx" for fast prototyping OR "wan" for final quality
   - notes describe the singer's intended mood / energy in this section
4. For B-ROLL scenes:
   - ref_image = ONE broll image (use exact filename)
   - prompt describes environment, camera, lighting (NO singer mentioned)
   - model = "ltx" for transitions OR "wan" for hero shots (choruses)
   - motion_strength: 0.3-0.8 (vary for visual interest)
   - notes describe the scene's role in pacing

RULES:
- Use ALL sections.
- Singer image should be the SAME across all singer scenes.
- Spread broll image usage — try to use each at least once.
- Total scene count: between {min_scenes} and {max_scenes}.

== OUTPUT FORMAT ==
Output a SINGLE valid JSON object (no markdown, no commentary):
{{
  "song_title": "...",
  "bpm": {bpm},
  "total_duration": {duration},
  "singer_ref_image": "<singer filename>",
  "scenes": [
    {{
      "index": 0,
      "start_time": 0.0,
      "end_time": 12.5,
      "section": "intro",
      "scene_type": "broll",
      "ref_image": "<broll filename>",
      "prompt": "...",
      "negative_prompt": "blurry, low quality, ...",
      "model": "ltx",
      "motion_strength": 0.4,
      "duration_sec": 12.5,
      "notes": "..."
    }},
    {{
      "index": 1,
      "start_time": 12.5,
      "end_time": 36.8,
      "section": "verse1",
      "scene_type": "singer_latentsync",
      "ref_image": "<singer filename>",
      "base_model": "wan",
      "vocal_audio_segment": "vocal_segment_001.wav",
      "prompt": "...",
      "negative_prompt": "blurry, distorted face, ...",
      "motion_strength": 0.3,
      "latentsync_mask_strength": 0.7,
      "duration_sec": 24.3,
      "notes": "..."
    }}
  ]
}}

For SINGER_LATENTSYNC scenes include: base_model ("ltx" or "wan"),
  motion_strength, latentsync_mask_strength, vocal_audio_segment.
For B-ROLL scenes include: model ("ltx" or "wan"), motion_strength.
"""


def build_prompt(beatmap, lyrics, singer_images, broll_images, song_title):
    sections_block = "\n".join(
        f"  - {i}. {s['label']:10s}  {s['start']:6.1f}s - {s['end']:6.1f}s  "
        f"vocal_active={s.get('vocal_active', 'unknown')}"
        for i, s in enumerate(beatmap["sections"])
    )
    singer_listing = "\n".join(f"  - {Path(p).name}" for p in singer_images) or "  (none)"
    broll_listing = "\n".join(f"  - {Path(p).name}" for p in broll_images) or "  (none)"
    n_sections = len(beatmap["sections"])
    min_scenes = max(n_sections, 6)
    max_scenes = min(n_sections * 2, 20)
    return DIRECTOR_PROMPT_TEMPLATE.format(
        title=song_title, bpm=beatmap["bpm"], duration=beatmap["duration_sec"],
        ts=beatmap["time_signature"], sections_block=sections_block,
        lyrics=lyrics or "(no lyrics provided — instrumental)",
        singer_listing=singer_listing, broll_listing=broll_listing,
        min_scenes=min_scenes, max_scenes=max_scenes,
    )


def main():
    p = argparse.ArgumentParser(description="LLM-directed shot list for LatentSync pipeline.")
    p.add_argument("--beatmap", required=True)
    p.add_argument("--lyrics", required=True)
    p.add_argument("--singer-dir", required=True)
    p.add_argument("--broll-dir", required=True)
    p.add_argument("--output", default="shotlist.json")
    p.add_argument("--title", default="Untitled")
    p.add_argument("--provider", choices=list(PROVIDERS.keys()), default="zai")
    p.add_argument("--model", default=None)
    p.add_argument("--temperature", type=float, default=0.8)
    p.add_argument("--max-tokens", type=int, default=10000)
    p.add_argument("--send-images", action="store_true")
    args = p.parse_args()

    with open(args.beatmap) as f:
        beatmap = json.load(f)
    with open(args.lyrics, encoding="utf-8") as f:
        lyrics = f.read().strip()

    ref_exts = {".png", ".jpg", ".jpeg", ".webp"}
    singer_dir = Path(args.singer_dir)
    broll_dir = Path(args.broll_dir)
    singer_images = sorted([str(p) for p in singer_dir.iterdir() if p.suffix.lower() in ref_exts])
    broll_images = sorted([str(p) for p in broll_dir.iterdir() if p.suffix.lower() in ref_exts])

    if not singer_images:
        print(f"ERROR: no singer reference images in {singer_dir}")
        sys.exit(1)
    if not broll_images:
        print(f"WARN: no B-roll reference images in {broll_dir}")

    print(f"[llm_shotlist_latentsync] Singer images: {len(singer_images)}")
    print(f"[llm_shotlist_latentsync] B-roll images: {len(broll_images)}")

    prompt = build_prompt(beatmap, lyrics, singer_images, broll_images, args.title)
    print(f"[llm_shotlist_latentsync] Prompt length: {len(prompt)} chars")

    caller, default_model = PROVIDERS[args.provider]
    model = args.model or default_model
    print(f"[llm_shotlist_latentsync] Calling {args.provider} / {model} ...")

    images_to_send = None
    if args.send_images:
        images_to_send = singer_images + broll_images
        print(f"[llm_shotlist_latentsync] Sending {len(images_to_send)} reference images as vision input")

    raw = caller(prompt, images_to_send, model, args.temperature, args.max_tokens)

    raw_stripped = raw.strip()
    if raw_stripped.startswith("```"):
        parts = raw_stripped.split("```")
        if len(parts) >= 3:
            raw_stripped = parts[1]
            if raw_stripped.startswith("json"):
                raw_stripped = raw_stripped[4:]
            raw_stripped = raw_stripped.strip("`\n ")

    try:
        shotlist = json.loads(raw_stripped)
    except json.JSONDecodeError as e:
        print(f"[llm_shotlist_latentsync] ERROR: LLM output was not valid JSON: {e}")
        with open("shotlist_raw.txt", "w", encoding="utf-8") as f:
            f.write(raw)
        print("[llm_shotlist_latentsync] Raw output saved to shotlist_raw.txt")
        sys.exit(1)

    if "scenes" not in shotlist or not isinstance(shotlist["scenes"], list):
        print("[llm_shotlist_latentsync] ERROR: shot list missing 'scenes' array")
        sys.exit(1)

    singer_basenames = {Path(p).name: p for p in singer_images}
    broll_basenames = {Path(p).name: p for p in broll_images}
    singer_ref_default = next(iter(singer_basenames.keys()))

    if "singer_ref_image" not in shotlist or shotlist["singer_ref_image"] not in singer_basenames:
        shotlist["singer_ref_image"] = singer_ref_default

    singer_count = 0
    broll_count = 0
    for i, sc in enumerate(shotlist["scenes"]):
        sc["index"] = i
        scene_type = sc.get("scene_type", "broll")
        if scene_type not in ("singer_latentsync", "broll"):
            print(f"[llm_shotlist_latentsync] WARN: scene {i} unknown scene_type '{scene_type}', defaulting to 'broll'")
            sc["scene_type"] = "broll"
            scene_type = "broll"

        if scene_type == "singer_latentsync":
            singer_count += 1
            sc["ref_image"] = shotlist["singer_ref_image"]
            sc["vocal_audio_segment"] = f"vocal_segment_{i:03d}.wav"
            sc.setdefault("base_model", "wan")
            if sc["base_model"] not in ("ltx", "wan"):
                sc["base_model"] = "wan"
            sc.setdefault("motion_strength", 0.3)
            # Cap motion_strength for LatentSync stability
            sc["motion_strength"] = min(float(sc["motion_strength"]), 0.4)
            sc.setdefault("latentsync_mask_strength", 0.7)
            sc.setdefault("negative_prompt",
                          "blurry, distorted face, deformed, asymmetric eyes, plastic skin, "
                          "extra teeth, melting face, bad anatomy, watermark, text, "
                          "extreme head motion, fast camera movement")
        else:
            broll_count += 1
            if sc.get("ref_image") not in broll_basenames:
                if broll_basenames:
                    sc["ref_image"] = next(iter(broll_basenames.keys()))
                else:
                    sc["ref_image"] = shotlist["singer_ref_image"]
            if sc.get("model") not in ("ltx", "wan"):
                sc["model"] = "wan"
            sc.setdefault("motion_strength", 0.5)
            sc.setdefault("negative_prompt",
                          "blurry, low quality, cartoon, anime, watermark, text, deformed, "
                          "distorted, bad anatomy, jpeg artifacts, oversaturated, plastic skin")

    Path(args.output).parent.mkdir(parents=True, exist_ok=True)
    with open(args.output, "w", encoding="utf-8") as f:
        json.dump(shotlist, f, indent=2)

    print(f"\n[llm_shotlist_latentsync] Wrote shot list to {args.output}")
    print(f"[llm_shotlist_latentsync] Total scenes: {len(shotlist['scenes'])}")
    print(f"[llm_shotlist_latentsync]   Singer (LatentSync): {singer_count}")
    print(f"[llm_shotlist_latentsync]   B-roll:             {broll_count}")
    print(f"[llm_shotlist_latentsync] Singer ref: {shotlist['singer_ref_image']}")
    print()
    for sc in shotlist["scenes"]:
        if sc["scene_type"] == "singer_latentsync":
            st = f"🎤 SINGER/{sc['base_model']:3s}"
        else:
            st = "  BROLL    "
        print(f"  Scene {sc['index']:2d}  {sc['start_time']:6.1f}-{sc['end_time']:6.1f}s  "
              f"[{sc['section']:10s}]  {st}  ref={sc['ref_image']}")


if __name__ == "__main__":
    main()
